# Experiments on ACL Dataset

In [2]:
import pandas as pd
import numpy as np
import matplotlib as plt
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import StandardScaler
from sklearn import svm
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.feature_selection import SelectFromModel
from sklearn.model_selection import cross_val_predict
from sklearn.model_selection import KFold
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
import seaborn as sns
from sklearn import tree
from sklearn.metrics import classification_report
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import GridSearchCV
from sklearn.utils import shuffle
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import RobustScaler
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import cross_val_score
from numpy import mean
from numpy import std

In [3]:
df = pd.read_csv("../alc_features.csv")
#df = shuffle(df)
#df.reset_index(inplace=True, drop=True)
df.drop('voiceID', inplace = True, axis = 1)
df['label'].value_counts()
df

meanF0Hz  stdevF0Hz        HNR  localJitter  localabsoluteJitter  \
0      231.866381  62.608349  14.910471     0.015804             0.000068   
1      230.594980  63.431316  14.771761     0.017727             0.000077   
2      268.836169  51.213756  13.583299     0.013771             0.000051   
3      228.111334  50.625133  12.975833     0.017943             0.000079   
4      242.185964  63.096325  14.811666     0.018676             0.000078   
...           ...        ...        ...          ...                  ...   
14321  187.210746  30.578724  14.852125     0.020264             0.000107   
14322  192.559848  22.355013  15.782604     0.020935             0.000109   
14323  197.592057  19.137307  16.010206     0.018847             0.000096   
14324  185.849489  27.278716  11.754181     0.035296             0.000190   
14325  202.729182  37.086329  17.451967     0.017436             0.000086   

       rapJitter  ppq5Jitter  localShimmer  localdbShimmer  apq3Shimmer  \
0       0.005720    0.006902      0.057241        0.587492     0.017015   
1       0.007172    0.007425      0.078143        0.773243     0.025503   
2       0.004716    0.005989      0.083791        0.742424     0.021311   
3       0.006881    0.008525      0.101454        0.951315     0.028647   
4       0.007180    0.007467      0.078560        0.750528     0.022424   
...          ...         ...           ...             ...          ...   
14321   0.007438    0.008985      0.094219        1.005321     0.035308   
14322   0.009105    0.009842      0.097997        0.912451     0.040760   
14323   0.006743    0.008801      0.081207        0.772486     0.030192   
14324   0.012950    0.013512      0.131805        1.051927     0.043271   
14325   0.006691    0.006843      0.075251        0.796122     0.029586   

       apq5Shimmer  label  
0         0.025154      1  
1         0.037667      1  
2         0.034554      1  
3         0.044857      1  
4         0.033239      1  
...            ...    ...  
14321     0.047885      0  
14322     0.048706      0  
14323     0.043843      0  
14324     0.078672      0  
14325     0.038882      0  

[14326 rows x 12 columns]

In [4]:
#separate dependent and independent variable
X = df.iloc[:, :-1]
df_X = df.iloc[:, :-1].values
df_Y = df.iloc[:,-1].values

# Split the dataset into the Training set and Test set
X_train, X_test, y_train, y_test = train_test_split(df_X, df_Y, test_size = 0.3, random_state = 0)

pd.DataFrame(X_train)


0          1          2         3         4         5  \
0      133.095250  27.103379   8.527502  0.043179  0.000325  0.019326   
1      140.718193  74.791819  12.860573  0.035252  0.000259  0.015130   
2      123.428665  13.891627  11.554429  0.030659  0.000248  0.010597   
3      144.969663  36.358087  14.000420  0.018041  0.000128  0.006822   
4      263.345208  53.309481  17.577684  0.026660  0.000102  0.012683   
...           ...        ...        ...       ...       ...       ...   
10023  204.024479  32.327157  20.564616  0.012995  0.000064  0.005765   
10024  103.344177  21.804353   9.112947  0.036795  0.000356  0.014469   
10025  257.648836  66.571241  11.956472  0.017766  0.000069  0.008288   
10026  130.562779  50.537988  13.918348  0.026354  0.000201  0.012046   
10027  119.922674  23.272796  10.848898  0.040318  0.000339  0.017064   

              6         7         8         9        10  
0      0.015723  0.104811  1.025456  0.035144  0.045718  
1      0.013691  0.095989  1.011781  0.031638  0.047728  
2      0.011987  0.113683  0.982335  0.032625  0.061170  
3      0.008868  0.088370  0.888016  0.022585  0.032361  
4      0.010293  0.055352  0.550730  0.016144  0.021382  
...         ...       ...       ...       ...       ...  
10023  0.005475  0.052426  0.603168  0.014569  0.023609  
10024  0.015388  0.131571  1.189652  0.043360  0.060488  
10025  0.007995  0.076234  0.763881  0.034123  0.045447  
10026  0.009966  0.088097  0.805158  0.037105  0.046047  
10027  0.016191  0.100913  0.988956  0.035915  0.053430  

[10028 rows x 11 columns]

### Feature scaling

In [5]:
# Scale
#sc = StandardScaler()
sc = MinMaxScaler()
#sc = RobustScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

pd.DataFrame(X_train)

0         1         2         3         4         5         6  \
0      0.170861  0.167955  0.254150  0.481847  0.448587  0.378782  0.350223   
1      0.199129  0.544966  0.451022  0.370945  0.347258  0.280276  0.292803   
2      0.135014  0.063507  0.391678  0.306685  0.330989  0.173862  0.244642   
3      0.214895  0.241120  0.502811  0.130148  0.147778  0.085252  0.156541   
4      0.653869  0.375133  0.665343  0.250735  0.108296  0.222827  0.196798   
...         ...       ...       ...       ...       ...       ...       ...   
10023  0.433889  0.209253  0.801053  0.059559  0.049104  0.060443  0.060672   
10024  0.060534  0.126063  0.280750  0.392526  0.495265  0.264768  0.340756   
10025  0.632745  0.479976  0.409944  0.126308  0.057266  0.119665  0.131867   
10026  0.161470  0.353222  0.499082  0.246455  0.259232  0.207874  0.187551   
10027  0.122013  0.137672  0.359622  0.441816  0.469240  0.325681  0.363425   

              7         8         9        10  
0      0.431222  0.519161  0.270494  0.254677  
1      0.377890  0.508895  0.233284  0.270322  
2      0.484856  0.486788  0.243756  0.374944  
3      0.331826  0.415980  0.137178  0.150710  
4      0.132222  0.162767  0.068809  0.065253  
...         ...       ...       ...       ...  
10023  0.114530  0.202134  0.052095  0.082591  
10024  0.592995  0.642429  0.357716  0.369637  
10025  0.258464  0.322787  0.259666  0.252569  
10026  0.330179  0.353775  0.291318  0.257233  
10027  0.407654  0.491759  0.278685  0.314700  

[10028 rows x 11 columns]

# *****************KNN Experiments******************

## Build model
### without tuning the hyperparameters

In [11]:
###### KNNN ###########
# Fit classifier to the Training set
#KNN
model_knn = KNeighborsClassifier(n_neighbors = 10)
model_knn.fit(X_train, y_train)

y_pred_knn = model_knn.predict(X_test)

conf_matrix_knn = confusion_matrix(y_test, y_pred_knn)

accuracy_knn = ((conf_matrix_knn[0,0] + conf_matrix_knn[1,1])/(conf_matrix_knn[0,0] +conf_matrix_knn[0,1]+conf_matrix_knn[1,0]+conf_matrix_knn[1,1]))*100


print(accuracy_knn)

#Checking performance our model with classification report.
print(classification_report(y_test, y_pred_knn))
#Checking performance our model with ROC Score.
print(roc_auc_score(y_test, y_pred_knn))

print(y_pred_knn)

print(conf_matrix_knn)

67.05444392740809
              precision    recall  f1-score   support

           0       0.69      0.91      0.79      2879
           1       0.50      0.18      0.27      1419

    accuracy                           0.67      4298
   macro avg       0.60      0.55      0.53      4298
weighted avg       0.63      0.67      0.62      4298

0.5469802592269211
[0 0 1 ... 1 0 0]
[[2622  257]
 [1159  260]]


## Hyperparameter tuning for KNN

In [8]:
########Hyperparameter tuning for KNN####################
#List Hyperparameters that we want to tune.
leaf_size = list(range(1,50))
n_neighbors = list(range(1,20)) #neighbours must be < number of samples (22)
p=[1,2]
#Convert to dictionary
hyperparameters = dict(leaf_size=leaf_size, n_neighbors=n_neighbors, p=p)
#Create new KNN object
knn_2 = KNeighborsClassifier()

cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)

#Use GridSearch
clf = GridSearchCV(knn_2, hyperparameters, cv=10)

#clf = RandomizedSearchCV(knn_2, hyperparameters, n_iter=500, cv=8, scoring="recall")
#Fit the model
best_model = clf.fit(X_train, y_train)
#Print The value of best Hyperparameters
print('Best leaf_size:', best_model.best_estimator_.get_params()['leaf_size'])
print('Best p:', best_model.best_estimator_.get_params()['p'])
print('Best n_neighbors:', best_model.best_estimator_.get_params()['n_neighbors'])
print('Best Score: %s' % best_model.best_score_)
print('Best Hyperparameters: %s' % best_model.best_params_)
print(hyperparameters)
y_pred_knn_2 = best_model.predict(X_test)

conf_matrix_knn_2 = confusion_matrix(y_test, y_pred_knn_2)

accuracy_knn_2 = ((conf_matrix_knn_2[0,0] + conf_matrix_knn_2[1,1])/(conf_matrix_knn_2[0,0] +conf_matrix_knn_2[0,1]+conf_matrix_knn_2[1,0]+conf_matrix_knn_2[1,1]))*100


print(accuracy_knn_2)

#Checking performance our model with classification report.
print(classification_report(y_test, y_pred_knn_2))
#Checking performance our model with ROC Score.
print(roc_auc_score(y_test, y_pred_knn_2))

print(y_pred_knn_2)
print(y_test)

print(conf_matrix_knn_2)

Best leaf_size: 1
Best p: 1
Best n_neighbors: 18
Best Score: 0.6772038292780216
Best Hyperparameters: {'leaf_size': 1, 'n_neighbors': 18, 'p': 1}
{'leaf_size': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49], 'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19], 'p': [1, 2]}
67.75244299674267
              precision    recall  f1-score   support

           0       0.69      0.93      0.79      2879
           1       0.54      0.17      0.26      1419

    accuracy                           0.68      4298
   macro avg       0.62      0.55      0.53      4298
weighted avg       0.64      0.68      0.62      4298

0.5484379241578528
[0 0 1 ... 0 0 0]
[0 0 1 ... 1 0 0]
[[2673  206]
 [1180  239]]


## Build Model
### using the optimal parameters gotten above

In [12]:
model_knn = KNeighborsClassifier(n_neighbors = 18, p = 1, leaf_size = 1)
model_knn.fit(X_train, y_train)

y_pred_knn = model_knn.predict(X_test)

conf_matrix_knn = confusion_matrix(y_test, y_pred_knn)

accuracy_knn = ((conf_matrix_knn[0,0] + conf_matrix_knn[1,1])/(conf_matrix_knn[0,0] +conf_matrix_knn[0,1]+conf_matrix_knn[1,0]+conf_matrix_knn[1,1]))*100


print(accuracy_knn)

#Checking performance our model with classification report.
print(classification_report(y_test, y_pred_knn))
#Checking performance our model with ROC Score.
print(roc_auc_score(y_test, y_pred_knn))

print(y_pred_knn)
print(y_test)
print(conf_matrix_knn)

67.75244299674267
              precision    recall  f1-score   support

           0       0.69      0.93      0.79      2879
           1       0.54      0.17      0.26      1419

    accuracy                           0.68      4298
   macro avg       0.62      0.55      0.53      4298
weighted avg       0.64      0.68      0.62      4298

0.5484379241578528
[0 0 1 ... 0 0 0]
[0 0 1 ... 1 0 0]
[[2673  206]
 [1180  239]]


## Evaluation 


### Evaluation with Leave one out method

In [13]:
df_X = sc.fit_transform(df_X)
k_fold = KFold(n_splits=37)
#KNN
model_knn_kfold = KNeighborsClassifier(n_neighbors = 18, p =1, leaf_size = 1)
y_pred_kfold_knn = cross_val_predict(model_knn_kfold, df_X, df_Y, cv=k_fold)

scores = cross_val_score(model_knn_kfold, df_X, df_Y, scoring='accuracy', cv=k_fold, n_jobs=-1)
# report performance
print('Accuracy: %.3f (%.3f)' % (mean(scores), std(scores)))

print(df_Y)
print(y_pred_kfold_knn)
conf_matrix_knn_kfold = confusion_matrix(df_Y, y_pred_kfold_knn)
print("Confusion Matrix for KNN using k-fold (leave one out)")
print(conf_matrix_knn_kfold)


accuracy_knn_2 = ((conf_matrix_knn_kfold[0,0] + conf_matrix_knn_kfold[1,1])/(conf_matrix_knn_kfold[0,0] +conf_matrix_knn_kfold[0,1]+conf_matrix_knn_kfold[1,0]+conf_matrix_knn_kfold[1,1]))*100


print(accuracy_knn_2)

Accuracy: 0.638 (0.355)
[1 1 1 ... 0 0 0]
[1 1 1 ... 0 0 0]
Confusion Matrix for KNN using k-fold (leave one out)
[[8525 1061]
 [4130  610]]
63.76518218623482


##### K Fold Evaluation using optimal paramaters. (k =5)


In [18]:
#df_kfold = shuffle(df)
#df_kfold.reset_index(inplace=True, drop=True)
from sklearn.model_selection import StratifiedKFold
df_kfold = df
df_Xnew = df_kfold.iloc[:, :-1].values
df_Ynew = df_kfold.iloc[:,-1].values


X_kfold = pd.DataFrame(df_Xnew)
y_kfold = pd.DataFrame(df_Ynew)
#print(X_kfold)
#print(y_kfold)

parts = 6
kfold = KFold(parts, True, None) 

# splits into 5 groups 
print("Divided into %s parts." %parts)

k_list = []

for i in range (1,12):
    row = []
    row.append(i)
    total = 0
    #print("Loop", i)
    for train, test in kfold.split(X_kfold,y_kfold):
        #print('\ntrain: %s, test: %s' % (train, test))
        Xtrain_kfold = X_kfold.iloc[train, :]
        Ytrain_kfold = y_kfold.iloc[train, :]
        Xtest_kfold = X_kfold.iloc[test, :]
        Ytest_kfold = y_kfold.iloc[test, :]
        #print(Xtest_kfold)
        #print(Ytest_kfold)
        #print(Ytrain_kfold)

        Xtrain_kfold = sc.fit_transform(Xtrain_kfold)
        Xtest_kfold = sc.transform(Xtest_kfold)

        #modelling
        model_knn_new = KNeighborsClassifier(n_neighbors = 18, p =1, leaf_size = 1)
        model_knn_new.fit(Xtrain_kfold, Ytrain_kfold)
        y_pred_knn_new = model_knn_new.predict(Xtest_kfold)

        conf_matrix_knn_kfold = confusion_matrix(Ytest_kfold, y_pred_knn_new)

        accuracy_knn_kfold = ((conf_matrix_knn_kfold[0,0] + conf_matrix_knn_kfold[1,1])/(conf_matrix_knn_kfold[0,0] +conf_matrix_knn_kfold[0,1]+conf_matrix_knn_kfold[1,0]+conf_matrix_knn_kfold[1,1]))*100

        #print("Confusion Matrix:\n ", conf_matrix_knn_kfold)
        #print("Accuracy ", accuracy_knn_kfold)

        row.append(accuracy_knn_kfold)
        total += accuracy_knn_kfold
    average = row.append(total/parts)
        
    #print(row)
    k_list.append(row)
    

k_list = pd.DataFrame(k_list, columns=['Loops','fold 1','fold 2','fold 3','fold 4', 'fold 5', 'fold 6', 'mean accuracy'])
print("KNN Kfold Evaluation for MDVR-KCL Dataset")
k_list
    

    
    
    
#print(df.sample(n=7))
#print(df)

#x = df.take(np.random.permutation(len(df))[:4])
#x= df.sample(n=7)
#print(x)
#print(df.drop(x))

#drop_indices = np.random.choice(df.index, 4, replace=False)
#df_subset = df.drop(drop_indices)
#print(drop_indices)
#print(df_subset)

    
    


Divided into 6 parts.


C:\Users\Aeesha\Anaconda3\lib\site-packages\ipykernel_launcher.py:42: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
C:\Users\Aeesha\Anaconda3\lib\site-packages\ipykernel_launcher.py:42: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
C:\Users\Aeesha\Anaconda3\lib\site-packages\ipykernel_launcher.py:42: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
C:\Users\Aeesha\Anaconda3\lib\site-packages\ipykernel_launcher.py:42: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
C:\Users\Aeesha\Anaconda3\lib\site-packages\ipykernel_launcher.py:42: DataConversionWarning: A c

C:\Users\Aeesha\Anaconda3\lib\site-packages\ipykernel_launcher.py:42: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
C:\Users\Aeesha\Anaconda3\lib\site-packages\ipykernel_launcher.py:42: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
C:\Users\Aeesha\Anaconda3\lib\site-packages\ipykernel_launcher.py:42: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
C:\Users\Aeesha\Anaconda3\lib\site-packages\ipykernel_launcher.py:42: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
C:\Users\Aeesha\Anaconda3\lib\site-packages\ipykernel_launcher.py:42: DataConversionWarning: A c

KNN Kfold Evaluation for MDVR-KCL Dataset


Loops     fold 1     fold 2     fold 3     fold 4     fold 5     fold 6  \
0       1  67.797320  67.629816  69.472362  67.713568  68.035191  66.401341   
1       2  67.755444  68.132328  68.467337  68.718593  67.113532  67.909510   
2       3  69.095477  67.922948  67.252931  66.959799  68.663594  67.532468   
3       4  68.927973  67.964824  68.467337  67.252931  67.364893  68.412233   
4       5  67.462312  69.388610  67.252931  69.179229  68.454127  66.778383   
5       6  68.257956  67.378559  67.294807  68.174204  68.621701  68.454127   
6       7  67.462312  69.639866  66.959799  67.839196  67.574361  66.736489   
7       8  67.964824  67.211055  67.336683  68.634841  68.286552  68.328446   
8       9  67.629816  67.587940  66.876047  67.713568  67.951403  68.286552   
9      10  66.541039  68.257956  69.053601  66.666667  67.867616  68.412233   
10     11  67.964824  67.964824  69.137353  66.499162  67.616255  67.700042   

    mean accuracy  
0       67.841599  
1       68.016124  
2       67.904536  
3       68.065032  
4       68.085932  
5       68.030226  
6       67.702004  
7       67.960400  
8       67.674221  
9       67.799852  
10      67.813743


# *****************Decision Tree Experiments***************

## Build model
### without tuning the hyperparameters

In [19]:
###### KNNN ###########
# Fit classifier to the Training set
#Decision Tree
import matplotlib.pyplot as plt
model_dt = tree.DecisionTreeClassifier()
model_dt = model_dt.fit(X_train, y_train)

y_pred_knn = model_dt.predict(X_test)

conf_matrix_knn = confusion_matrix(y_test, y_pred_knn)

accuracy_knn = ((conf_matrix_knn[0,0] + conf_matrix_knn[1,1])/(conf_matrix_knn[0,0] +conf_matrix_knn[0,1]+conf_matrix_knn[1,0]+conf_matrix_knn[1,1]))*100


print(accuracy_knn)

#Checking performance our model with classification report.
print(classification_report(y_test, y_pred_knn))
#Checking performance our model with ROC Score.
print(roc_auc_score(y_test, y_pred_knn))

print(y_pred_knn)

print(conf_matrix_knn)

#plt.figure(figsize=(24,14))
#tree.plot_tree(model_dt, filled=True, fontsize=14)

58.81805490926012
              precision    recall  f1-score   support

           0       0.69      0.69      0.69      2879
           1       0.38      0.39      0.38      1419

    accuracy                           0.59      4298
   macro avg       0.54      0.54      0.54      4298
weighted avg       0.59      0.59      0.59      4298

0.5374991952857329
[0 0 1 ... 1 1 1]
[[1977  902]
 [ 868  551]]


## Hyperparameter tuning for Decision Trees

In [21]:
########Hyperparameter tuning for KNN####################
#List Hyperparameters that we want to tune.
#n_components = list(range(1,X.shape[1]+1,1))
max_depth = list(range(1,10))
min_samples_split = list(range(2,10)) #neighbours must be < number of samples (22)
min_samples_leaf = list(range(1,5))
criterion=['gini','entropy']
#Convert to dictionary
hyperparameters = dict(max_depth=max_depth, min_samples_split=min_samples_split, min_samples_leaf=min_samples_leaf, criterion = criterion)
#Create new KNN object
dt_2 = tree.DecisionTreeClassifier()

cv = RepeatedStratifiedKFold(n_splits=4, n_repeats=3, random_state=1)

#Use GridSearch
clf = GridSearchCV(dt_2, hyperparameters, refit=True, cv=10)

#clf = RandomizedSearchCV(knn_2, hyperparameters, n_iter=500, cv=8, scoring="recall")
#Fit the model
best_model = clf.fit(X_train, y_train)
#Print The value of best Hyperparameters
#print('Best leaf_size:', best_model.best_estimator_.get_params()['leaf_size'])
#print('Best p:', best_model.best_estimator_.get_params()['p'])
#print('Best n_neighbors:', best_model.best_estimator_.get_params()['n_neighbors'])
print('Best Score: %s' % best_model.best_score_)
print('Best Hyperparameters: %s' % best_model.best_params_)
print(hyperparameters)
y_pred_knn_2 = best_model.predict(X_test)

conf_matrix_knn_2 = confusion_matrix(y_test, y_pred_knn_2)

accuracy_knn_2 = ((conf_matrix_knn_2[0,0] + conf_matrix_knn_2[1,1])/(conf_matrix_knn_2[0,0] +conf_matrix_knn_2[0,1]+conf_matrix_knn_2[1,0]+conf_matrix_knn_2[1,1]))*100


print(accuracy_knn_2)

#Checking performance our model with classification report.
print(classification_report(y_test, y_pred_knn_2))
#Checking performance our model with ROC Score.
print(roc_auc_score(y_test, y_pred_knn_2))

print(y_pred_knn_2)
print(y_test)

print(conf_matrix_knn_2)

Best Score: 0.6753091344236138
Best Hyperparameters: {'criterion': 'entropy', 'max_depth': 4, 'min_samples_leaf': 4, 'min_samples_split': 2}
{'max_depth': [1, 2, 3, 4, 5, 6, 7, 8, 9], 'min_samples_split': [2, 3, 4, 5, 6, 7, 8, 9], 'min_samples_leaf': [1, 2, 3, 4], 'criterion': ['gini', 'entropy']}
66.79851093531876
              precision    recall  f1-score   support

           0       0.69      0.93      0.79      2879
           1       0.49      0.14      0.21      1419

    accuracy                           0.67      4298
   macro avg       0.59      0.53      0.50      4298
weighted avg       0.62      0.67      0.60      4298

0.5332763730261245
[0 0 1 ... 1 0 0]
[0 0 1 ... 1 0 0]
[[2677  202]
 [1225  194]]


## Build Model (Decision Tree)
### using the optimal parameters gotten above

In [23]:
#model_dt = tree.DecisionTreeClassifier(max_depth = 6, criterion='entropy',min_samples_leaf=2, min_samples_split=2 )
model_dt = tree.DecisionTreeClassifier(max_depth = 4, criterion='entropy',min_samples_leaf=4, min_samples_split=2 )
model_dt = model_dt.fit(X_train, y_train)

y_pred_dt_2 = best_model.predict(X_test)

conf_matrix_dt_2 = confusion_matrix(y_test, y_pred_dt_2)

accuracy_dt_2 = ((conf_matrix_dt_2[0,0] + conf_matrix_dt_2[1,1])/(conf_matrix_dt_2[0,0] +conf_matrix_dt_2[0,1]+conf_matrix_dt_2[1,0]+conf_matrix_dt_2[1,1]))*100

print(conf_matrix_dt_2)
print(accuracy_dt_2)

[[2677  202]
 [1225  194]]
66.79851093531876


## Evaluation 


### Evaluation with Leave one out method

In [24]:
df_X = sc.fit_transform(df_X)
k_fold = KFold(n_splits=14326)
#KNN
#model_knn_kfold = tree.DecisionTreeClassifier(max_depth = 6, criterion='entropy',min_samples_leaf=2, min_samples_split=2 )
model_dt = tree.DecisionTreeClassifier(max_depth = 4, criterion='entropy',min_samples_leaf=4, min_samples_split=2)
y_pred_kfold_knn = cross_val_predict(model_dt, df_X, df_Y, cv=k_fold)
scores = cross_val_score(model_dt, df_X, df_Y, scoring='accuracy', cv=k_fold, n_jobs=-1)
# report performance
print('Accuracy: %.3f (%.3f)' % (mean(scores), std(scores)))

print(df_Y)
print(y_pred_kfold_knn)
conf_matrix_knn_kfold = confusion_matrix(df_Y, y_pred_kfold_knn)
print("Confusion Matrix for Dt using k-fold (leave one out)")
print(conf_matrix_knn_kfold)


accuracy_knn_2 = ((conf_matrix_knn_kfold[0,0] + conf_matrix_knn_kfold[1,1])/(conf_matrix_knn_kfold[0,0] +conf_matrix_knn_kfold[0,1]+conf_matrix_knn_kfold[1,0]+conf_matrix_knn_kfold[1,1]))*100


print(accuracy_knn_2)

Accuracy: 0.682 (0.466)
[1 1 1 ... 0 0 0]
[0 1 1 ... 1 0 1]
Confusion Matrix for Dt using k-fold (leave one out)
[[8920  666]
 [3891  849]]
68.19070221974033


### K Fold Evaluation using optimal paramaters. (k =4)


In [25]:
#df_kfold = shuffle(df)
#df_kfold.reset_index(inplace=True, drop=True)
from sklearn.model_selection import StratifiedKFold
df_kfold = df
df_Xnew = df_kfold.iloc[:, :-1].values
df_Ynew = df_kfold.iloc[:,-1].values


X_kfold = pd.DataFrame(df_Xnew)
y_kfold = pd.DataFrame(df_Ynew)
#print(X_kfold)
#print(y_kfold)

parts = 6
kfold = KFold(parts, True, None) 

# splits into 5 groups 
print("Divided into %s parts." %parts)

k_list = []

for i in range (1,12):
    row = []
    row.append(i)
    total = 0
    #print("Loop", i)
    for train, test in kfold.split(X_kfold,y_kfold):
        #print('\ntrain: %s, test: %s' % (train, test))
        Xtrain_kfold = X_kfold.iloc[train, :]
        Ytrain_kfold = y_kfold.iloc[train, :]
        Xtest_kfold = X_kfold.iloc[test, :]
        Ytest_kfold = y_kfold.iloc[test, :]
        #print(Xtest_kfold)
        #print(Ytest_kfold)

        Xtrain_kfold = sc.fit_transform(Xtrain_kfold)
        Xtest_kfold = sc.transform(Xtest_kfold)

        #modelling
        #model_knn_new = tree.DecisionTreeClassifier(max_depth = 6, criterion='entropy',min_samples_leaf=2, min_samples_split=2 )
        model_dt_new = tree.DecisionTreeClassifier(max_depth = 4, criterion='entropy',min_samples_leaf=4, min_samples_split=2)
        model_dt_new.fit(Xtrain_kfold, Ytrain_kfold)
        y_pred_dt_new = model_dt_new.predict(Xtest_kfold)

        conf_matrix_dt_kfold = confusion_matrix(Ytest_kfold, y_pred_dt_new)

        accuracy_dt_kfold = ((conf_matrix_dt_kfold[0,0] + conf_matrix_dt_kfold[1,1])/(conf_matrix_dt_kfold[0,0] +conf_matrix_dt_kfold[0,1]+conf_matrix_dt_kfold[1,0]+conf_matrix_dt_kfold[1,1]))*100

        #print("Confusion Matrix:\n ", conf_matrix_knn_kfold)
        #print("Accuracy ", accuracy_knn_kfold)

        row.append(accuracy_dt_kfold)
        total += accuracy_dt_kfold
    average = row.append(total/parts)
        
    #print(row)
    k_list.append(row)
    
k_list = pd.DataFrame(k_list, columns=['Loops','fold 1','fold 2','fold 3','fold 4','fold 5','fold 6', 'mean accuracy'])
print("Decsion Tree Kfold Evaluation for MDVR-KCL Dataset")
k_list
    

    
    
    
#print(df.sample(n=7))
#print(df)

#x = df.take(np.random.permutation(len(df))[:4])
#x= df.sample(n=7)
#print(x)
#print(df.drop(x))

#drop_indices = np.random.choice(df.index, 4, replace=False)
#df_subset = df.drop(drop_indices)
#print(drop_indices)
#print(df_subset)

    
    


Divided into 6 parts.
Decsion Tree Kfold Evaluation for MDVR-KCL Dataset


Loops     fold 1     fold 2     fold 3     fold 4     fold 5     fold 6  \
0       1  65.326633  66.457286  66.624791  68.341709  67.825723  68.537914   
1       2  66.331658  65.242881  67.378559  68.509213  67.490574  67.071638   
2       3  67.587940  66.624791  66.541039  68.216080  67.281106  67.616255   
3       4  66.917923  67.336683  68.048576  67.252931  66.945957  67.658148   
4       5  65.745394  68.048576  68.216080  66.541039  67.700042  68.035191   
5       6  67.964824  66.373534  66.750419  66.541039  68.579807  67.364893   
6       7  67.294807  67.127303  68.551089  64.656616  66.527021  67.616255   
7       8  68.592965  67.504188  67.462312  68.718593  65.060746  66.275660   
8       9  67.001675  66.834171  67.336683  68.551089  67.448680  67.113532   
9      10  66.373534  68.090452  66.792295  68.216080  66.652702  65.982405   
10     11  67.294807  66.582915  66.959799  67.629816  66.652702  67.658148   

    mean accuracy  
0       67.185676  
1       67.004087  
2       67.311202  
3       67.360037  
4       67.381054  
5       67.262419  
6       66.962182  
7       67.269077  
8       67.380972  
9       67.017911  
10      67.129698


# *****************SVM Experiments***************

## Build model
### without tuning the hyperparameters

In [26]:
###### KNNN ###########
# Fit classifier to the Training set
#Decision Tree
import matplotlib.pyplot as plt
model_svm = svm.SVC()
model_svm = model_dt.fit(X_train, y_train)

y_pred_svm = model_dt.predict(X_test)

conf_matrix_svm = confusion_matrix(y_test, y_pred_svm)

accuracy_svm = ((conf_matrix_svm[0,0] + conf_matrix_svm[1,1])/(conf_matrix_svm[0,0] +conf_matrix_svm[0,1]+conf_matrix_svm[1,0]+conf_matrix_svm[1,1]))*100


print(accuracy_svm)

#Checking performance our model with classification report.
print(classification_report(y_test, y_pred_svm))
#Checking performance our model with ROC Score.
print(roc_auc_score(y_test, y_pred_svm))

print(y_pred_svm)

print(conf_matrix_svm)


66.79851093531876
              precision    recall  f1-score   support

           0       0.69      0.93      0.79      2879
           1       0.49      0.14      0.21      1419

    accuracy                           0.67      4298
   macro avg       0.59      0.53      0.50      4298
weighted avg       0.62      0.67      0.60      4298

0.5332763730261245
[0 0 1 ... 1 0 0]
[[2677  202]
 [1225  194]]


## Hyperparameter tuning for SVM

In [27]:
########Hyperparameter tuning for SVM####################
#List Hyperparameters that we want to tune.
#n_components = list(range(1,X.shape[1]+1,1))
C = [0.1, 1, 10, 100, 1000]
gamma = [1, 0.1, 0.01, 0.001, 0.0001]
kernel = ['rbf']

#Convert to dictionary
hyperparameters = dict(C=C, gamma=gamma, kernel=kernel)
#Create new KNN object
svm2 = svm.SVC()

cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)

#Use GridSearch
clf = GridSearchCV(svm2, hyperparameters, refit=True)

#clf = RandomizedSearchCV(knn_2, hyperparameters, n_iter=500, cv=8, scoring="recall")
#Fit the model
best_model = clf.fit(X_train, y_train)
#Print The value of best Hyperparameters
#print('Best leaf_size:', best_model.best_estimator_.get_params()['leaf_size'])
#print('Best p:', best_model.best_estimator_.get_params()['p'])
#print('Best n_neighbors:', best_model.best_estimator_.get_params()['n_neighbors'])
print('Best Score: %s' % best_model.best_score_)
print('Best Hyperparameters: %s' % best_model.best_params_)
print(hyperparameters)
y_pred_knn_2 = best_model.predict(X_test)

conf_matrix_knn_2 = confusion_matrix(y_test, y_pred_knn_2)

accuracy_knn_2 = ((conf_matrix_knn_2[0,0] + conf_matrix_knn_2[1,1])/(conf_matrix_knn_2[0,0] +conf_matrix_knn_2[0,1]+conf_matrix_knn_2[1,0]+conf_matrix_knn_2[1,1]))*100


print(accuracy_knn_2)

#Checking performance our model with classification report.
print(classification_report(y_test, y_pred_knn_2))
#Checking performance our model with ROC Score.
print(roc_auc_score(y_test, y_pred_knn_2))

print(y_pred_knn_2)
print(y_test)

print(conf_matrix_knn_2)

C:\Users\Aeesha\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


Best Score: 0.6849820502592741
Best Hyperparameters: {'C': 1000, 'gamma': 1, 'kernel': 'rbf'}
{'C': [0.1, 1, 10, 100, 1000], 'gamma': [1, 0.1, 0.01, 0.001, 0.0001], 'kernel': ['rbf']}
68.07817589576547
              precision    recall  f1-score   support

           0       0.69      0.97      0.80      2879
           1       0.60      0.10      0.17      1419

    accuracy                           0.68      4298
   macro avg       0.64      0.53      0.49      4298
weighted avg       0.66      0.68      0.59      4298

0.5337151411854353
[0 0 1 ... 0 0 0]
[0 0 1 ... 1 0 0]
[[2783   96]
 [1276  143]]


## Build Model (SVM)
### using the optimal parameters gotten above

In [28]:
model_svm = svm.SVC(C = 1000, gamma=1,kernel='rbf')
model_svm = model_svm.fit(X_train, y_train)

y_pred_svm_2 = best_model.predict(X_test)

conf_matrix_svm_2 = confusion_matrix(y_test, y_pred_svm_2)

accuracy_svm_2 = ((conf_matrix_svm_2[0,0] + conf_matrix_svm_2[1,1])/(conf_matrix_svm_2[0,0] +conf_matrix_svm_2[0,1]+conf_matrix_svm_2[1,0]+conf_matrix_svm_2[1,1]))*100

print(conf_matrix_svm_2)
print(accuracy_svm_2)

[[2783   96]
 [1276  143]]
68.07817589576547


## Evaluation (SVM) 


### Evaluation with Leave one out method

In [ ]:
df_X = sc.fit_transform(df_X)
k_fold = KFold(n_splits=14326)
#KNN
#model_knn_kfold = tree.DecisionTreeClassifier(max_depth = 6, criterion='entropy',min_samples_leaf=2, min_samples_split=2 )
model_svm = svm.SVC(C = 1000, gamma=1,kernel='rbf')
y_pred_kfold_svm = cross_val_predict(model_svm, df_X, df_Y, cv=k_fold)
scores = cross_val_score(model_svm, df_X, df_Y, scoring='accuracy', cv=k_fold, n_jobs=-1)
# report performance
print('Accuracy: %.3f (%.3f)' % (mean(scores), std(scores)))

print(df_Y)
print(y_pred_kfold_knn)
conf_matrix_svm_kfold = confusion_matrix(df_Y, y_pred_kfold_svm)
print("Confusion Matrix for Dt using k-fold (leave one out)")
print(conf_matrix_svm_kfold)


accuracy_svm_2 = ((conf_matrix_svm_kfold[0,0] + conf_matrix_svm_kfold[1,1])/(conf_matrix_svm_kfold[0,0] +conf_matrix_svm_kfold[0,1]+conf_matrix_svm_kfold[1,0]+conf_matrix_svm_kfold[1,1]))*100


print(accuracy_svm_2)

### K Fold Evaluation using optimal paramaters. (k =4)


In [ ]:
#df_kfold = shuffle(df)
#df_kfold.reset_index(inplace=True, drop=True)
from sklearn.model_selection import StratifiedKFold
df_kfold = df
df_Xnew = df_kfold.iloc[:, :-1].values
df_Ynew = df_kfold.iloc[:,-1].values


X_kfold = pd.DataFrame(df_Xnew)
y_kfold = pd.DataFrame(df_Ynew)
#print(X_kfold)
#print(y_kfold)

parts = 6
kfold = KFold(parts, True, None) 

# splits into 5 groups 
print("Divided into %s parts." %parts)

k_list = []

for i in range (1,12):
    row = []
    row.append(i)
    total = 0
    #print("Loop", i)
    for train, test in kfold.split(X_kfold,y_kfold):
        #print('\ntrain: %s, test: %s' % (train, test))
        Xtrain_kfold = X_kfold.iloc[train, :]
        Ytrain_kfold = y_kfold.iloc[train, :]
        Xtest_kfold = X_kfold.iloc[test, :]
        Ytest_kfold = y_kfold.iloc[test, :]
        #print(Xtest_kfold)
        #print(Ytest_kfold)

        Xtrain_kfold = sc.fit_transform(Xtrain_kfold)
        Xtest_kfold = sc.transform(Xtest_kfold)

        #modelling
        #model_knn_new = tree.DecisionTreeClassifier(max_depth = 6, criterion='entropy',min_samples_leaf=2, min_samples_split=2 )
        model_svm_new = svm.SVC(C = 1000, gamma=1,kernel='rbf')
        model_svm_new.fit(Xtrain_kfold, Ytrain_kfold)
        y_pred_svm_new = model_svm_new.predict(Xtest_kfold)

        conf_matrix_svm_kfold = confusion_matrix(Ytest_kfold, y_pred_svm_new)

        accuracy_svm_kfold = ((conf_matrix_svm_kfold[0,0] + conf_matrix_svm_kfold[1,1])/(conf_matrix_svm_kfold[0,0] +conf_matrix_svm_kfold[0,1]+conf_matrix_svm_kfold[1,0]+conf_matrix_svm_kfold[1,1]))*100

        #print("Confusion Matrix:\n ", conf_matrix_knn_kfold)
        #print("Accuracy ", accuracy_knn_kfold)

        row.append(accuracy_svm_kfold)
        total += accuracy_svm_kfold
    average = row.append(total/parts)
    #print(row)
    k_list.append(row)
    
k_list = pd.DataFrame(k_list, columns=['Loops','fold 1','fold 2','fold 3','fold 4','fold 5','fold 6', 'mean accuracy'])
print("SVM Kfold Evaluation for MDVR-KCL Dataset")
k_list
    

    
    
    
#print(df.sample(n=7))
#print(df)

#x = df.take(np.random.permutation(len(df))[:4])
#x= df.sample(n=7)
#print(x)
#print(df.drop(x))

#drop_indices = np.random.choice(df.index, 4, replace=False)
#df_subset = df.drop(drop_indices)
#print(drop_indices)
#print(df_subset)

    
    



# *****************Naive Bayes Experiments***************

## Build model
### without tuning the hyperparameters

In [5]:
###### KNNN ###########
# Fit classifier to the Training set
#NB
model_nb = GaussianNB()
model_nb = model_nb.fit(X_train, y_train)


y_pred_nb = model_nb.predict(X_test)

conf_matrix_nb = confusion_matrix(y_test, y_pred_nb)

accuracy_nb = ((conf_matrix_nb[0,0] + conf_matrix_nb[1,1])/(conf_matrix_nb[0,0] +conf_matrix_nb[0,1]+conf_matrix_nb[1,0]+conf_matrix_nb[1,1]))*100


print(accuracy_nb)

#Checking performance our model with classification report.
print(classification_report(y_test, y_pred_nb))
#Checking performance our model with ROC Score.
print(roc_auc_score(y_test, y_pred_nb))

print(y_pred_nb)

print(conf_matrix_nb)


56.49139134481154
              precision    recall  f1-score   support

           0       0.71      0.59      0.65      2879
           1       0.38      0.50      0.43      1419

    accuracy                           0.56      4298
   macro avg       0.54      0.55      0.54      4298
weighted avg       0.60      0.56      0.58      4298

0.5496158055428474
[0 1 1 ... 1 1 1]
[[1712 1167]
 [ 703  716]]


## Hyperparameter tuning for Naive Bayes

### NB doesnt have important parameters to tune

## Evaluation (Naive Bayes) 


### Evaluation with Leave one out method

In [7]:
df_X = sc.fit_transform(df_X)
k_fold = KFold(n_splits=37)
#KNN
#model_knn_kfold = tree.DecisionTreeClassifier(max_depth = 6, criterion='entropy',min_samples_leaf=2, min_samples_split=2 )
model_nb_2 = GaussianNB()
y_pred_kfold_nb = cross_val_predict(model_nb_2, df_X, df_Y, cv=k_fold)
scores = cross_val_score(model_nb_2, df_X, df_Y, scoring='accuracy', cv=k_fold, n_jobs=-1)
# report performance
print('Accuracy: %.3f (%.3f)' % (mean(scores), std(scores)))

print(df_Y)
print(y_pred_kfold_nb)
conf_matrix_nb_kfold = confusion_matrix(df_Y, y_pred_kfold_nb)
print("Confusion Matrix for Dt using k-fold (leave one out)")
print(conf_matrix_nb_kfold)


accuracy_nb_2 = ((conf_matrix_nb_kfold[0,0] + conf_matrix_nb_kfold[1,1])/(conf_matrix_nb_kfold[0,0] +conf_matrix_nb_kfold[0,1]+conf_matrix_nb_kfold[1,0]+conf_matrix_nb_kfold[1,1]))*100


print(accuracy_nb_2)

Accuracy: 0.757 (0.429)
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
[1 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 0 0 1 1 1 1 1 0 1 0 0]
Confusion Matrix for Dt using k-fold (leave one out)
[[17  4]
 [ 5 11]]
75.67567567567568


### K Fold Evaluation using optimal paramaters. (k =4)


In [8]:
#df_kfold = shuffle(df)
#df_kfold.reset_index(inplace=True, drop=True)
from sklearn.model_selection import StratifiedKFold
df_kfold = df
df_Xnew = df_kfold.iloc[:, :-1].values
df_Ynew = df_kfold.iloc[:,-1].values


X_kfold = pd.DataFrame(df_Xnew)
y_kfold = pd.DataFrame(df_Ynew)
#print(X_kfold)
#print(y_kfold)

parts = 6
kfold = KFold(parts, True, None) 

# splits into 5 groups 
print("Divided into %s parts." %parts)

k_list = []

for i in range (1,12):
    row = []
    row.append(i)
    total = 0
    #print("Loop", i)
    for train, test in kfold.split(X_kfold,y_kfold):
        #print('\ntrain: %s, test: %s' % (train, test))
        Xtrain_kfold = X_kfold.iloc[train, :]
        Ytrain_kfold = y_kfold.iloc[train, :]
        Xtest_kfold = X_kfold.iloc[test, :]
        Ytest_kfold = y_kfold.iloc[test, :]
        #print(Xtest_kfold)
        #print(Ytest_kfold)

        Xtrain_kfold = sc.fit_transform(Xtrain_kfold)
        Xtest_kfold = sc.transform(Xtest_kfold)
        

        #modelling
        #model_knn_new = tree.DecisionTreeClassifier(max_depth = 6, criterion='entropy',min_samples_leaf=2, min_samples_split=2 )
        model_nb_new = GaussianNB()
        model_nb_new.fit(Xtrain_kfold, Ytrain_kfold)

        y_pred_nb_new = model_nb_new.predict(Xtest_kfold)

        conf_matrix_nb_kfold = confusion_matrix(Ytest_kfold, y_pred_nb_new)

        accuracy_nb_kfold = ((conf_matrix_nb_kfold[0,0] + conf_matrix_nb_kfold[1,1])/(conf_matrix_nb_kfold[0,0] +conf_matrix_nb_kfold[0,1]+conf_matrix_nb_kfold[1,0]+conf_matrix_nb_kfold[1,1]))*100

        #print("Confusion Matrix:\n ", conf_matrix_knn_kfold)
        #print("Accuracy ", accuracy_knn_kfold)

        row.append(accuracy_nb_kfold)
        total += accuracy_nb_kfold
    average = row.append(total/parts)
    #print(row)
    k_list.append(row)
    
k_list = pd.DataFrame(k_list, columns=['Loops','fold 1','fold 2','fold 3','fold 4', 'fold 5','fold 6', 'mean accuracy'])
print("SVM Kfold Evaluation for MDVR-KCL Dataset")
k_list
    

    
    
    
#print(df.sample(n=7))
#print(df)

#x = df.take(np.random.permutation(len(df))[:4])
#x= df.sample(n=7)
#print(x)
#print(df.drop(x))

#drop_indices = np.random.choice(df.index, 4, replace=False)
#df_subset = df.drop(drop_indices)
#print(drop_indices)
#print(df_subset)

    
    


Divided into 6 parts.


C:\Users\Aeesha\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Aeesha\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Aeesha\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Aeesha\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,

C:\Users\Aeesha\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Aeesha\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Aeesha\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Aeesha\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,

SVM Kfold Evaluation for MDVR-KCL Dataset


C:\Users\Aeesha\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Aeesha\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Aeesha\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Aeesha\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,

Loops     fold 1     fold 2     fold 3     fold 4     fold 5     fold 6  \
0       1  57.118928  56.742044  55.820771  56.281407  59.195643  56.849602   
1       2  58.752094  55.569514  56.783920  57.872697  58.357771  55.509007   
2       3  56.700168  56.783920  58.877722  55.276382  56.598240  57.561793   
3       4  56.030151  56.072027  57.579564  58.835846  56.263092  57.436112   
4       5  56.993300  57.077052  59.128978  56.239531  55.341433  57.561793   
5       6  56.783920  54.983250  56.532663  57.621441  57.813155  58.944282   
6       7  55.946399  58.207705  56.574539  57.412060  57.017176  57.310432   
7       8  55.569514  58.249581  57.453936  57.998325  56.807708  56.514453   
8       9  58.458961  56.532663  56.072027  56.993300  56.807708  57.561793   
9      10  56.783920  58.333333  58.919598  54.480737  55.090071  58.441558   
10     11  58.040201  57.328308  54.857621  55.862647  57.519899  58.022623   

    mean accuracy  
0       57.001399  
1       57.140834  
2       56.966371  
3       57.036132  
4       57.057014  
5       57.113118  
6       57.078052  
7       57.098920  
8       57.071075  
9       57.008203  
10      56.938550


# *****************Logistic Regression Experiments***************

## Build model
### without tuning the hyperparameters

In [9]:
###### KNNN ###########
# Fit classifier to the Training set
#NB


model_lr = LogisticRegression(random_state=0)
model_lr = model_lr.fit(X_train, y_train)

y_pred_lr = model_lr.predict(X_test)

conf_matrix_lr = confusion_matrix(y_test, y_pred_lr)

accuracy_lr = ((conf_matrix_lr[0,0] + conf_matrix_lr[1,1])/(conf_matrix_lr[0,0] +conf_matrix_lr[0,1]+conf_matrix_lr[1,0]+conf_matrix_lr[1,1]))*100


print(accuracy_lr)

#Checking performance our model with classification report.
print(classification_report(y_test, y_pred_lr))
#Checking performance our model with ROC Score.
print(roc_auc_score(y_test, y_pred_lr))

print(y_pred_lr)

print(conf_matrix_lr)


C:\Users\Aeesha\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


67.17077710563053
              precision    recall  f1-score   support

           0       0.68      0.98      0.80      2879
           1       0.53      0.05      0.09      1419

    accuracy                           0.67      4298
   macro avg       0.60      0.51      0.45      4298
weighted avg       0.63      0.67      0.57      4298

0.5142550083824913
[0 0 0 ... 0 0 0]
[[2815   64]
 [1347   72]]


## Hyperparameter tuning for LR

In [11]:
########Hyperparameter tuning for SVM####################
#List Hyperparameters that we want to tune.
#n_components = list(range(1,X.shape[1]+1,1))
solvers = ['newton-cg', 'lbfgs', 'liblinear']
penalty = ['l2']
c_values = [100, 10, 1.0, 0.1, 0.01]

#Convert to dictionary
hyperparameters = dict(solver=solvers,penalty=penalty,C=c_values)
#Create new LR object
model_lr2 = LogisticRegression()

cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)

#Use GridSearch
clf = GridSearchCV(model_lr2, hyperparameters, cv=cv)

#clf = RandomizedSearchCV(knn_2, hyperparameters, n_iter=500, cv=8, scoring="recall")
#Fit the model
best_model = clf.fit(X_train, y_train)
#Print The value of best Hyperparameters
#print('Best leaf_size:', best_model.best_estimator_.get_params()['leaf_size'])
#print('Best p:', best_model.best_estimator_.get_params()['p'])
#print('Best n_neighbors:', best_model.best_estimator_.get_params()['n_neighbors'])
print('Best Score: %s' % best_model.best_score_)
print('Best Hyperparameters: %s' % best_model.best_params_)
print(hyperparameters)
y_pred_knn_2 = best_model.predict(X_test)

conf_matrix_knn_2 = confusion_matrix(y_test, y_pred_knn_2)

accuracy_knn_2 = ((conf_matrix_knn_2[0,0] + conf_matrix_knn_2[1,1])/(conf_matrix_knn_2[0,0] +conf_matrix_knn_2[0,1]+conf_matrix_knn_2[1,0]+conf_matrix_knn_2[1,1]))*100


print(accuracy_knn_2)

#Checking performance our model with classification report.
print(classification_report(y_test, y_pred_knn_2))
#Checking performance our model with ROC Score.
print(roc_auc_score(y_test, y_pred_knn_2))

print(y_pred_knn_2)
print(y_test)

print(conf_matrix_knn_2)

C:\Users\Aeesha\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:947: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
C:\Users\Aeesha\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:947: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)


Best Score: 0.6801622124717458
Best Hyperparameters: {'C': 100, 'penalty': 'l2', 'solver': 'liblinear'}
{'solver': ['newton-cg', 'lbfgs', 'liblinear'], 'penalty': ['l2'], 'C': [100, 10, 1.0, 0.1, 0.01]}
67.44997673336435
              precision    recall  f1-score   support

           0       0.68      0.97      0.80      2879
           1       0.55      0.08      0.14      1419

    accuracy                           0.67      4298
   macro avg       0.61      0.52      0.47      4298
weighted avg       0.64      0.67      0.58      4298

0.5242013991135537
[0 0 1 ... 0 0 0]
[0 0 1 ... 1 0 0]
[[2783   96]
 [1303  116]]


## Build Model (LR)
### using the optimal parameters gotten above

In [16]:
model_lr = LogisticRegression(C= 100, penalty='l2',solver= 'liblinear')
model_lr = model_lr.fit(X_train, y_train)

y_pred_lr_2 = best_model.predict(X_test)

conf_matrix_lr_2 = confusion_matrix(y_test, y_pred_lr_2)

accuracy_lr_2 = ((conf_matrix_lr_2[0,0] + conf_matrix_lr_2[1,1])/(conf_matrix_lr_2[0,0] +conf_matrix_lr_2[0,1]+conf_matrix_lr_2[1,0]+conf_matrix_lr_2[1,1]))*100

print(conf_matrix_lr_2)
print(accuracy_lr_2)

[[2783   96]
 [1303  116]]
67.44997673336435


## Evaluation (LR) 


### K Fold Evaluation using optimal paramaters. (k =4)


In [17]:
#df_kfold = shuffle(df)
#df_kfold.reset_index(inplace=True, drop=True)
from sklearn.model_selection import StratifiedKFold
df_kfold = df
df_Xnew = df_kfold.iloc[:, :-1].values
df_Ynew = df_kfold.iloc[:,-1].values


X_kfold = pd.DataFrame(df_Xnew)
y_kfold = pd.DataFrame(df_Ynew)
#print(X_kfold)
#print(y_kfold)

parts = 6
kfold = KFold(parts, True, None) 

# splits into 5 groups 
print("Divided into %s parts." %parts)

k_list = []

for i in range (1,12):
    row = []
    row.append(i)
    total = 0
    #print("Loop", i)
    for train, test in kfold.split(X_kfold,y_kfold):
        #print('\ntrain: %s, test: %s' % (train, test))
        Xtrain_kfold = X_kfold.iloc[train, :]
        Ytrain_kfold = y_kfold.iloc[train, :]
        Xtest_kfold = X_kfold.iloc[test, :]
        Ytest_kfold = y_kfold.iloc[test, :]
        #print(Xtest_kfold)
        #print(Ytest_kfold)

        Xtrain_kfold = sc.fit_transform(Xtrain_kfold)
        Xtest_kfold = sc.transform(Xtest_kfold)
        

        #modelling
        #model_knn_new = tree.DecisionTreeClassifier(max_depth = 6, criterion='entropy',min_samples_leaf=2, min_samples_split=2 )
        model_nb_new = LogisticRegression(C= 100, penalty='l2',solver= 'liblinear')
        model_nb_new.fit(Xtrain_kfold, Ytrain_kfold)

        y_pred_nb_new = model_nb_new.predict(Xtest_kfold)

        conf_matrix_nb_kfold = confusion_matrix(Ytest_kfold, y_pred_nb_new)

        accuracy_nb_kfold = ((conf_matrix_nb_kfold[0,0] + conf_matrix_nb_kfold[1,1])/(conf_matrix_nb_kfold[0,0] +conf_matrix_nb_kfold[0,1]+conf_matrix_nb_kfold[1,0]+conf_matrix_nb_kfold[1,1]))*100

        #print("Confusion Matrix:\n ", conf_matrix_knn_kfold)
        #print("Accuracy ", accuracy_knn_kfold)

        row.append(accuracy_nb_kfold)
        total += accuracy_nb_kfold
    average = row.append(total/parts)
    #print(row)
    k_list.append(row)
    
k_list = pd.DataFrame(k_list, columns=['Loops','fold 1','fold 2','fold 3','fold 4','fold 5','fold 6', 'mean accuracy'])
print("LR Kfold Evaluation for MDVR-KCL Dataset")
k_list
    

    
    
    
#print(df.sample(n=7))
#print(df)

#x = df.take(np.random.permutation(len(df))[:4])
#x= df.sample(n=7)
#print(x)
#print(df.drop(x))

#drop_indices = np.random.choice(df.index, 4, replace=False)
#df_subset = df.drop(drop_indices)
#print(drop_indices)
#print(df_subset)

    
    


Divided into 6 parts.


C:\Users\Aeesha\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Aeesha\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Aeesha\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Aeesha\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,

C:\Users\Aeesha\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Aeesha\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Aeesha\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Aeesha\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,

LR Kfold Evaluation for MDVR-KCL Dataset


C:\Users\Aeesha\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Aeesha\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Loops     fold 1     fold 2     fold 3     fold 4     fold 5     fold 6  \
0       1  67.378559  68.676717  67.127303  67.211055  67.448680  69.166318   
1       2  68.886097  68.132328  66.666667  69.430486  66.610809  67.406787   
2       3  67.797320  67.839196  68.676717  66.415410  68.286552  68.160871   
3       4  68.257956  67.546064  67.211055  68.090452  68.621701  68.035191   
4       5  69.304858  68.048576  67.336683  67.755444  67.867616  66.820276   
5       6  69.137353  66.792295  67.043551  67.881072  68.537914  67.783829   
6       7  67.964824  68.048576  66.666667  68.216080  68.328446  67.658148   
7       8  68.090452  66.624791  66.959799  68.006700  68.621701  68.873062   
8       9  66.750419  67.504188  68.760469  69.346734  67.867616  67.071638   
9      10  68.216080  68.509213  68.927973  68.802345  66.862170  66.275660   
10     11  67.252931  67.294807  67.378559  67.587940  67.574361  69.962296   

    mean accuracy  
0       67.834772  
1       67.855529  
2       67.862678  
3       67.960403  
4       67.855576  
5       67.862669  
6       67.813790  
7       67.862751  
8       67.883511  
9       67.932240  
10      67.841816


# *****************Gradient Boosting Experiments***************

## Build model
### without tuning the hyperparameters

In [8]:
###### KNNN ###########
# Fit classifier to the Training set
#NB

model_gb = GradientBoostingClassifier(random_state=0)
model_gb = model_gb.fit(X_train, y_train)

y_pred_gb = model_gb.predict(X_test)

conf_matrix_gb = confusion_matrix(y_test, y_pred_gb)

accuracy_gb = ((conf_matrix_gb[0,0] + conf_matrix_gb[1,1])/(conf_matrix_gb[0,0] +conf_matrix_gb[0,1]+conf_matrix_gb[1,0]+conf_matrix_gb[1,1]))*100


print(accuracy_gb)

#Checking performance our model with classification report.
print(classification_report(y_test, y_pred_gb))
#Checking performance our model with ROC Score.
print(roc_auc_score(y_test, y_pred_gb))

print(y_pred_gb)

print(conf_matrix_gb)


67.91530944625407
              precision    recall  f1-score   support

           0       0.69      0.95      0.80      2879
           1       0.56      0.13      0.21      1419

    accuracy                           0.68      4298
   macro avg       0.62      0.54      0.51      4298
weighted avg       0.65      0.68      0.61      4298

0.5403617750564769
[0 0 1 ... 0 0 0]
[[2732  147]
 [1232  187]]


## Hyperparameter tuning for Gradient Boosting

In [9]:
########Hyperparameter tuning for SVM####################
#List Hyperparameters that we want to tune.
#n_components = list(range(1,X.shape[1]+1,1))
n_estimators = [1, 2, 4, 8, 16, 32, 64, 100, 200] #[5,50,250,500]
max_depth = [1,3,5,7,9]
learning_rate = [1, 0.5, 0.25, 0.1, 0.05, 0.01] #[0.01,0.1,1,10,100] 

#Convert to dictionary
hyperparameters = dict(n_estimators=n_estimators,max_depth=max_depth,learning_rate=learning_rate)

#Create new LR object
model_gb2 = GradientBoostingClassifier()

cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)

#Use GridSearch
clf = GridSearchCV(model_gb2, hyperparameters, cv=10)

#clf = RandomizedSearchCV(knn_2, hyperparameters, n_iter=500, cv=8, scoring="recall")
#Fit the model
best_model = clf.fit(X_train, y_train)
#Print The value of best Hyperparameters
#print('Best leaf_size:', best_model.best_estimator_.get_params()['leaf_size'])
#print('Best p:', best_model.best_estimator_.get_params()['p'])
#print('Best n_neighbors:', best_model.best_estimator_.get_params()['n_neighbors'])
print('Best Score: %s' % best_model.best_score_)
print('Best Hyperparameters: %s' % best_model.best_params_)
print(hyperparameters)
y_pred_knn_2 = best_model.predict(X_test)

conf_matrix_knn_2 = confusion_matrix(y_test, y_pred_knn_2)

accuracy_knn_2 = ((conf_matrix_knn_2[0,0] + conf_matrix_knn_2[1,1])/(conf_matrix_knn_2[0,0] +conf_matrix_knn_2[0,1]+conf_matrix_knn_2[1,0]+conf_matrix_knn_2[1,1]))*100


print(accuracy_knn_2)

#Checking performance our model with classification report.
print(classification_report(y_test, y_pred_knn_2))
#Checking performance our model with ROC Score.
print(roc_auc_score(y_test, y_pred_knn_2))

print(y_pred_knn_2)
print(y_test)

print(conf_matrix_knn_2)

Best Score: 0.6861786996410052
Best Hyperparameters: {'learning_rate': 0.25, 'max_depth': 3, 'n_estimators': 16}
{'n_estimators': [1, 2, 4, 8, 16, 32, 64, 100, 200], 'max_depth': [1, 3, 5, 7, 9], 'learning_rate': [1, 0.5, 0.25, 0.1, 0.05, 0.01]}
68.054909260121
              precision    recall  f1-score   support

           0       0.69      0.95      0.80      2879
           1       0.57      0.13      0.21      1419

    accuracy                           0.68      4298
   macro avg       0.63      0.54      0.50      4298
weighted avg       0.65      0.68      0.60      4298

0.5399742883082544
[0 0 1 ... 0 0 0]
[0 0 1 ... 1 0 0]
[[2746  133]
 [1240  179]]


## Build Model (GB)
### using the optimal parameters gotten above

In [14]:
model_gb = GradientBoostingClassifier(learning_rate= 0.25, max_depth=3,n_estimators=16)
model_gb = model_gb.fit(X_train, y_train)

y_pred_gb_2 = model_gb.predict(X_test)

conf_matrix_gb_2 = confusion_matrix(y_test, y_pred_gb_2)

accuracy_gb_2 = ((conf_matrix_gb_2[0,0] + conf_matrix_gb_2[1,1])/(conf_matrix_gb_2[0,0] +conf_matrix_gb_2[0,1]+conf_matrix_gb_2[1,0]+conf_matrix_gb_2[1,1]))*100

print(conf_matrix_gb_2)
print(accuracy_gb_2)

[[2746  133]
 [1240  179]]
68.054909260121


## Evaluation (GB) 


### K Fold Evaluation using optimal paramaters. (k =4)


In [22]:
#df_kfold = shuffle(df)
#df_kfold.reset_index(inplace=True, drop=True)
from sklearn.model_selection import StratifiedKFold
df_kfold = df
df_Xnew = df_kfold.iloc[:, :-1].values
df_Ynew = df_kfold.iloc[:,-1].values


X_kfold = pd.DataFrame(df_Xnew)
y_kfold = pd.DataFrame(df_Ynew)
#print(X_kfold)
#print(y_kfold)

parts = 6
kfold = KFold(parts, True, None) 

# splits into 5 groups 
print("Divided into %s parts." %parts)

k_list = []

for i in range (1,12):
    row = []
    row.append(i)
    total = 0
    #print("Loop", i)
    for train, test in kfold.split(X_kfold,y_kfold):
        #print('\ntrain: %s, test: %s' % (train, test))
        Xtrain_kfold = X_kfold.iloc[train, :]
        Ytrain_kfold = y_kfold.iloc[train, :]
        Xtest_kfold = X_kfold.iloc[test, :]
        Ytest_kfold = y_kfold.iloc[test, :]
        #print(Xtest_kfold)
        #print(Ytest_kfold)

        Xtrain_kfold = sc.fit_transform(Xtrain_kfold)
        Xtest_kfold = sc.transform(Xtest_kfold)
        

        #modelling
        #model_knn_new = tree.DecisionTreeClassifier(max_depth = 6, criterion='entropy',min_samples_leaf=2, min_samples_split=2 )
        model_nb_new = GradientBoostingClassifier(learning_rate= 0.25, max_depth=3,n_estimators=16)
        model_nb_new.fit(Xtrain_kfold, Ytrain_kfold)

        y_pred_nb_new = model_nb_new.predict(Xtest_kfold)

        conf_matrix_nb_kfold = confusion_matrix(Ytest_kfold, y_pred_nb_new)

        accuracy_nb_kfold = ((conf_matrix_nb_kfold[0,0] + conf_matrix_nb_kfold[1,1])/(conf_matrix_nb_kfold[0,0] +conf_matrix_nb_kfold[0,1]+conf_matrix_nb_kfold[1,0]+conf_matrix_nb_kfold[1,1]))*100

        #print("Confusion Matrix:\n ", conf_matrix_knn_kfold)
        #print("Accuracy ", accuracy_knn_kfold)

        row.append(accuracy_nb_kfold)
        total += accuracy_nb_kfold
    average = row.append(total/parts)
    #print(row)
    k_list.append(row)
    
k_list = pd.DataFrame(k_list, columns=['Loops','fold 1','fold 2','fold 3','fold 4','fold 5', 'fold 6', 'mean accuracy'])
print("Gradient Boosting Kfold Evaluation for MDVR-KCL Dataset")
k_list
    

       
    


Divided into 6 parts.


C:\Users\Aeesha\Anaconda3\lib\site-packages\sklearn\ensemble\gradient_boosting.py:1450: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Aeesha\Anaconda3\lib\site-packages\sklearn\ensemble\gradient_boosting.py:1450: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Aeesha\Anaconda3\lib\site-packages\sklearn\ensemble\gradient_boosting.py:1450: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Aeesha\Anaconda3\lib\site-packages\sklearn\ensemble\gradient_boosting.py:1450: DataConversionWarning: A column-vector y was passed when a 1d array was expected.

C:\Users\Aeesha\Anaconda3\lib\site-packages\sklearn\ensemble\gradient_boosting.py:1450: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Aeesha\Anaconda3\lib\site-packages\sklearn\ensemble\gradient_boosting.py:1450: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Aeesha\Anaconda3\lib\site-packages\sklearn\ensemble\gradient_boosting.py:1450: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Aeesha\Anaconda3\lib\site-packages\sklearn\ensemble\gradient_boosting.py:1450: DataConversionWarning: A column-vector y was passed when a 1d array was expected.

C:\Users\Aeesha\Anaconda3\lib\site-packages\sklearn\ensemble\gradient_boosting.py:1450: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Aeesha\Anaconda3\lib\site-packages\sklearn\ensemble\gradient_boosting.py:1450: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Aeesha\Anaconda3\lib\site-packages\sklearn\ensemble\gradient_boosting.py:1450: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Aeesha\Anaconda3\lib\site-packages\sklearn\ensemble\gradient_boosting.py:1450: DataConversionWarning: A column-vector y was passed when a 1d array was expected.

Gradient Boosting Kfold Evaluation for MDVR-KCL Dataset


Loops     fold 1     fold 2     fold 3     fold 4     fold 5     fold 6  \
0       1  69.137353  67.964824  68.299832  68.844221  67.616255  68.705488   
1       2  68.174204  67.504188  69.346734  67.629816  68.831169  68.412233   
2       3  69.681742  67.294807  67.797320  68.886097  68.496020  68.077084   
3       4  68.090452  69.304858  68.802345  69.472362  66.694596  67.825723   
4       5  67.546064  67.294807  68.048576  68.216080  69.752828  69.208211   
5       6  67.336683  69.807370  67.755444  69.514238  68.831169  67.700042   
6       7  69.849246  68.048576  68.467337  68.090452  68.412233  67.364893   
7       8  68.257956  70.268007  67.462312  69.095477  67.029744  68.914956   
8       9  68.299832  65.787270  67.922948  67.713568  69.710934  70.171764   
9      10  68.090452  66.331658  69.849246  68.090452  68.663594  68.454127   
10     11  68.174204  69.346734  69.179229  69.430486  66.275660  67.197319   

    mean accuracy  
0       68.427996  
1       68.316391  
2       68.372178  
3       68.365056  
4       68.344428  
5       68.490824  
6       68.372123  
7       68.504742  
8       68.267719  
9       68.246588  
10      68.267272

# *****************Random Forest Experiments***************

## Build model
## without tuning the hyperparameters

In [16]:
###### KNNN ###########
# Fit classifier to the Training set
#NB

model_gb = RandomForestClassifier()
model_gb = model_gb.fit(X_train, y_train)

y_pred_gb = model_gb.predict(X_test)

conf_matrix_gb = confusion_matrix(y_test, y_pred_gb)

accuracy_gb = ((conf_matrix_gb[0,0] + conf_matrix_gb[1,1])/(conf_matrix_gb[0,0] +conf_matrix_gb[0,1]+conf_matrix_gb[1,0]+conf_matrix_gb[1,1]))*100


print(accuracy_gb)

#Checking performance our model with classification report.
print(classification_report(y_test, y_pred_gb))
#Checking performance our model with ROC Score.
print(roc_auc_score(y_test, y_pred_gb))

print(y_pred_gb)

print(conf_matrix_gb)


C:\Users\Aeesha\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


66.86831084225221
              precision    recall  f1-score   support

           0       0.70      0.89      0.78      2879
           1       0.50      0.23      0.31      1419

    accuracy                           0.67      4298
   macro avg       0.60      0.56      0.55      4298
weighted avg       0.63      0.67      0.63      4298

0.5563122521449461
[0 0 1 ... 1 1 0]
[[2554  325]
 [1099  320]]


## Hyperparameter tuning for Random Forest

In [17]:
########Hyperparameter tuning for SVM####################
#List Hyperparameters that we want to tune.
#n_components = list(range(1,X.shape[1]+1,1))
n_estimators = [1, 2, 4, 8, 16, 32, 64, 100, 200] #[5,50,250,500]
max_depth = [1,3,5,7,9]
max_features = ['auto', 'sqrt', 'log2'] #[0.01,0.1,1,10,100] 
min_samples_split = [2,5,10]
min_samples_leaf = [1,2,5,10,15]

#Convert to dictionary
hyperparameters = dict(n_estimators=n_estimators,max_depth=max_depth,max_features=max_features, min_samples_split=min_samples_split,min_samples_leaf=min_samples_leaf )

#Create new LR object
model_gb2 = RandomForestClassifier()

cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)

#Use GridSearch
clf = GridSearchCV(model_gb2, hyperparameters, cv=10)

#clf = RandomizedSearchCV(knn_2, hyperparameters, n_iter=500, cv=8, scoring="recall")
#Fit the model
best_model = clf.fit(X_train, y_train)
#Print The value of best Hyperparameters
#print('Best leaf_size:', best_model.best_estimator_.get_params()['leaf_size'])
#print('Best p:', best_model.best_estimator_.get_params()['p'])
#print('Best n_neighbors:', best_model.best_estimator_.get_params()['n_neighbors'])
print('Best Score: %s' % best_model.best_score_)
print('Best Hyperparameters: %s' % best_model.best_params_)
print(hyperparameters)
y_pred_knn_2 = best_model.predict(X_test)

conf_matrix_knn_2 = confusion_matrix(y_test, y_pred_knn_2)

accuracy_knn_2 = ((conf_matrix_knn_2[0,0] + conf_matrix_knn_2[1,1])/(conf_matrix_knn_2[0,0] +conf_matrix_knn_2[0,1]+conf_matrix_knn_2[1,0]+conf_matrix_knn_2[1,1]))*100


print(accuracy_knn_2)

#Checking performance our model with classification report.
print(classification_report(y_test, y_pred_knn_2))
#Checking performance our model with ROC Score.
print(roc_auc_score(y_test, y_pred_knn_2))

print(y_pred_knn_2)
print(y_test)

print(conf_matrix_knn_2)

Best Score: 0.6884722776226566
Best Hyperparameters: {'max_depth': 9, 'max_features': 'log2', 'min_samples_leaf': 1, 'min_samples_split': 10, 'n_estimators': 64}
{'n_estimators': [1, 2, 4, 8, 16, 32, 64, 100, 200], 'max_depth': [1, 3, 5, 7, 9], 'max_features': ['auto', 'sqrt', 'log2'], 'min_samples_split': [2, 5, 10], 'min_samples_leaf': [1, 2, 5, 10, 15]}
68.24104234527687
              precision    recall  f1-score   support

           0       0.69      0.95      0.80      2879
           1       0.58      0.14      0.22      1419

    accuracy                           0.68      4298
   macro avg       0.64      0.54      0.51      4298
weighted avg       0.65      0.68      0.61      4298

0.5440440006746137
[0 0 1 ... 0 0 0]
[0 0 1 ... 1 0 0]
[[2739  140]
 [1225  194]]


## Build Model (Random Forest)
### using the optimal parameters gotten above

In [20]:
model_gb = RandomForestClassifier(n_estimators=64,max_depth=9,max_features='log2', min_samples_split=10,min_samples_leaf=1)
model_gb = model_gb.fit(X_train, y_train)

y_pred_gb_2 = model_gb.predict(X_test)

conf_matrix_gb_2 = confusion_matrix(y_test, y_pred_gb_2)

accuracy_gb_2 = ((conf_matrix_gb_2[0,0] + conf_matrix_gb_2[1,1])/(conf_matrix_gb_2[0,0] +conf_matrix_gb_2[0,1]+conf_matrix_gb_2[1,0]+conf_matrix_gb_2[1,1]))*100

print(conf_matrix_gb_2)
print(accuracy_gb_2)

[[2736  143]
 [1230  189]]
68.054909260121


## Evaluation (RF) 


### K Fold Evaluation using optimal paramaters. (k =4)


In [23]:
#df_kfold = shuffle(df)
#df_kfold.reset_index(inplace=True, drop=True)
from sklearn.model_selection import StratifiedKFold
df_kfold = df
df_Xnew = df_kfold.iloc[:, :-1].values
df_Ynew = df_kfold.iloc[:,-1].values


X_kfold = pd.DataFrame(df_Xnew)
y_kfold = pd.DataFrame(df_Ynew)
#print(X_kfold)
#print(y_kfold)

parts = 6
kfold = KFold(parts, True, None) 

# splits into 5 groups 
print("Divided into %s parts." %parts)

k_list = []

for i in range (1,12):
    row = []
    row.append(i)
    total = 0
    #print("Loop", i)
    for train, test in kfold.split(X_kfold,y_kfold):
        #print('\ntrain: %s, test: %s' % (train, test))
        Xtrain_kfold = X_kfold.iloc[train, :]
        Ytrain_kfold = y_kfold.iloc[train, :]
        Xtest_kfold = X_kfold.iloc[test, :]
        Ytest_kfold = y_kfold.iloc[test, :]
        #print(Xtest_kfold)
        #print(Ytest_kfold)

        Xtrain_kfold = sc.fit_transform(Xtrain_kfold)
        Xtest_kfold = sc.transform(Xtest_kfold)
        

        #modelling
        #model_knn_new = tree.DecisionTreeClassifier(max_depth = 6, criterion='entropy',min_samples_leaf=2, min_samples_split=2 )
        model_nb_new = RandomForestClassifier(n_estimators=64,max_depth=9,max_features='log2', min_samples_split=10,min_samples_leaf=1)
        model_nb_new.fit(Xtrain_kfold, Ytrain_kfold)

        y_pred_nb_new = model_nb_new.predict(Xtest_kfold)

        conf_matrix_nb_kfold = confusion_matrix(Ytest_kfold, y_pred_nb_new)

        accuracy_nb_kfold = ((conf_matrix_nb_kfold[0,0] + conf_matrix_nb_kfold[1,1])/(conf_matrix_nb_kfold[0,0] +conf_matrix_nb_kfold[0,1]+conf_matrix_nb_kfold[1,0]+conf_matrix_nb_kfold[1,1]))*100

        #print("Confusion Matrix:\n ", conf_matrix_knn_kfold)
        #print("Accuracy ", accuracy_knn_kfold)

        row.append(accuracy_nb_kfold)
        total += accuracy_nb_kfold
    average = row.append(total/parts)
    #print(row)
    k_list.append(row)
    
k_list = pd.DataFrame(k_list, columns=['Loops','fold 1','fold 2','fold 3','fold 4','fold 5','fold 6', 'mean accuracy'])
print("Gradient Boosting Kfold Evaluation for MDVR-KCL Dataset")
k_list
    

       
    


Divided into 6 parts.


C:\Users\Aeesha\Anaconda3\lib\site-packages\ipykernel_launcher.py:43: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
C:\Users\Aeesha\Anaconda3\lib\site-packages\ipykernel_launcher.py:43: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
C:\Users\Aeesha\Anaconda3\lib\site-packages\ipykernel_launcher.py:43: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
C:\Users\Aeesha\Anaconda3\lib\site-packages\ipykernel_launcher.py:43: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
C:\Users\Aeesha\Anaconda3\lib\site-packages\ipykernel_launcher.py:43: DataConversionWarning: A colum

C:\Users\Aeesha\Anaconda3\lib\site-packages\ipykernel_launcher.py:43: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
C:\Users\Aeesha\Anaconda3\lib\site-packages\ipykernel_launcher.py:43: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
C:\Users\Aeesha\Anaconda3\lib\site-packages\ipykernel_launcher.py:43: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
C:\Users\Aeesha\Anaconda3\lib\site-packages\ipykernel_launcher.py:43: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
C:\Users\Aeesha\Anaconda3\lib\site-packages\ipykernel_launcher.py:43: DataConversionWarning: A colum

Gradient Boosting Kfold Evaluation for MDVR-KCL Dataset


Loops     fold 1     fold 2     fold 3     fold 4     fold 5     fold 6  \
0       1  67.420436  68.467337  69.974874  67.922948  68.789275  67.993297   
1       2  68.592965  69.388610  68.551089  69.137353  68.789275  67.700042   
2       3  68.132328  69.262982  67.252931  68.216080  69.585253  68.789275   
3       4  68.592965  68.509213  67.797320  68.802345  67.783829  69.669041   
4       5  69.053601  68.886097  67.881072  69.974874  69.124424  67.490574   
5       6  68.634841  69.974874  67.211055  68.216080  69.040637  68.244659   
6       7  66.834171  69.807370  68.634841  69.514238  67.406787  68.914956   
7       8  67.922948  69.472362  69.765494  68.927973  67.783829  69.166318   
8       9  69.137353  68.006700  68.592965  68.090452  68.035191  69.836615   
9      10  68.634841  68.383585  68.341709  69.262982  68.956850  68.621701   
10     11  68.718593  69.723618  69.556114  66.876047  68.118978  69.669041   

    mean accuracy  
0       68.428028  
1       68.693222  
2       68.539808  
3       68.525785  
4       68.735107  
5       68.553691  
6       68.518727  
7       68.839821  
8       68.616546  
9       68.700278  
10      68.777065